# Generated by Django 2.2.2 on 2019-06-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipoSeguroCobertura', models.CharField(max_length=30)),
                ('ocupacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('paginaWeb', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=50)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Convenio')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilRequerimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=80)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Perfil')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Requerimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajar', models.CharField(max_length=200)),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Condicion')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Facultad')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Provincia'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Pais'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Escuela'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Institucion'),
        ),
        migrations.AddField(
            model_name='condicion',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Convenio'),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compEspecificas', models.CharField(max_length=200)),
                ('compGenericas', models.CharField(max_length=200)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.PlanDeCapacitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('beneficiado', models.CharField(max_length=100)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Convenio')),
            ],
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=30)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionPrincipal', models.CharField(max_length=50)),
                ('tareasDerivadas', models.CharField(max_length=200)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.PlanDeCapacitacion')),
            ],
        ),
    ]
